# Generated by Django 4.2.20 on 2025-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['hash'], name='idx_files_hash'),
        ),
    ]
