# Generated by Django 4.2.20 on 2025-04-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_storagemetadata_storagemetadata_singleton_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='idx_files_hash',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type', 'size', 'uploaded_at'], name='idx_file_composite'),
        ),
    ]
