# Generated by Django 4.2.20 on 2025-04-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_file_idx_files_hash_alter_file_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemetadata',
            name='storage_saved_bytes',
        ),
    ]
