# Generated by Django 4.2.20 on 2025-04-27 14:24

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_storagemetadata_storage_saved_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to=files.models.file_upload_path),
        ),
    ]
